server:
  port: 8085
  servlet:
    contextPath: /auth

spring:
  application:
    name: auth

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/discovery/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'