server:
  port: 8761

spring:
  application:
    name: discovery
 
eureka:
  dashboard:
    path: /dashboard
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost