server:
  port: 8083

spring:
  application:
    name: gateway

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5

zuul:
  routes:
    discovery:
      path: /discovery/**
      serviceId: discovery
      sensitive-headers: Set-Cookie,Authorization
    resource-server:
      path: /resource-server/**
      serviceId: resource-server
      sensitive-headers: Set-Cookie,Authorization
       
hystrix:
  command:
    discovery:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
            
management:
  endpoints:
    web:
      exposure:
        include: '*'