# Make the application available at http://localhost:8080
# These are default settings, but we add them for clarity.
server:
  port: 8083

spring:
  application:
    name: gateway

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5

zuul:
  routes:
    discovery:
      path: /discovery/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://localhost:8761
    resource-server:
      path: /resource-server/**
      sensitive-headers: Set-Cookie,Authorization
      url: http://localhost:8084
       
hystrix:
  command:
    discovery:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
            
management:
  endpoints:
    web:
      exposure:
        include: '*'
       

# Configure the Authorization Server and User Info Resource Server details
security:
  oauth2:
    client:
      accessTokenUri: http://localhost:7070/authserver/oauth/token
      userAuthorizationUri: http://localhost:7070/authserver/oauth/authorize
      clientId: authserver
      clientSecret: passwordforauthserver
    resource:
      userInfoUri: http://localhost:9000/user

person:
  url: http://localhost:9000/person

# Make sure the OAuth2 token is only relayed when using the internal API,
# do not pass any authentication to the external API
proxy:
  auth:
    routes:
      api: oauth2